version: '3.8'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4865:4865"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - DB=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: